import { type Interviewer, type Interview, type Feedback, type User } from './types'

export const mockUser: User = {
  id: 'user-1',
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://avatar.vercel.sh/user?u=johndoe',
  role: 'candidate',
  bio: 'Software engineer looking to improve interview skills',
  resumeUrl: 'https://example.com/resume.pdf',
}

export const mockInterviewers: Interviewer[] = [
  {
    id: 'interviewer-1',
    name: 'Sarah Chen',
    company: 'Google',
    role: 'Senior Software Engineer',
    experience: 8,
    avatar: 'https://avatar.vercel.sh/user?u=sarahchen',
    bio: 'Passionate about helping others crack the coding interview. Specialized in DSA and system design.',
    skills: ['System Design', 'DSA', 'Java', 'Python', 'Go'],
    rating: 4.9,
    reviewCount: 342,
    pricePerSession: 120,
    nextAvailable: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    availability: [
      { day: 'Monday', times: ['9:00 AM', '2:00 PM', '5:00 PM'] },
      { day: 'Wednesday', times: ['10:00 AM', '3:00 PM'] },
      { day: 'Friday', times: ['9:00 AM', '1:00 PM', '6:00 PM'] },
    ],
  },
  {
    id: 'interviewer-2',
    name: 'Michael Park',
    company: 'Meta',
    role: 'Tech Lead',
    experience: 10,
    avatar: 'https://avatar.vercel.sh/user?u=michaelpark',
    bio: 'Former Tech Lead at Meta. Expert in behavioral interviews and system architecture.',
    skills: ['Behavioral', 'System Design', 'Leadership', 'C++', 'JavaScript'],
    rating: 4.8,
    reviewCount: 289,
    pricePerSession: 150,
    nextAvailable: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    availability: [
      { day: 'Tuesday', times: ['4:00 PM', '6:00 PM'] },
      { day: 'Thursday', times: ['2:00 PM', '5:00 PM'] },
      { day: 'Saturday', times: ['10:00 AM', '2:00 PM'] },
    ],
  },
  {
    id: 'interviewer-3',
    name: 'Alex Rodriguez',
    company: 'Amazon',
    role: 'Senior Engineer',
    experience: 7,
    avatar: 'https://avatar.vercel.sh/user?u=alexrodriguez',
    bio: 'Specialized in Amazon hiring process. Great at explaining complex problems simply.',
    skills: ['DSA', 'HR Interview', 'Python', 'JavaScript', 'Debugging'],
    rating: 4.7,
    reviewCount: 156,
    pricePerSession: 100,
    nextAvailable: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    availability: [
      { day: 'Monday', times: ['11:00 AM', '4:00 PM'] },
      { day: 'Wednesday', times: ['9:00 AM', '2:00 PM'] },
      { day: 'Friday', times: ['10:00 AM', '3:00 PM'] },
    ],
  },
  {
    id: 'interviewer-4',
    name: 'Emma Johnson',
    company: 'Microsoft',
    role: 'Product Manager',
    experience: 9,
    avatar: 'https://avatar.vercel.sh/user?u=emmajohnson',
    bio: 'PM at Microsoft. Expert in product management interviews and case studies.',
    skills: ['PM Interview', 'Case Study', 'Behavioral', 'Analytics', 'Strategy'],
    rating: 4.9,
    reviewCount: 198,
    pricePerSession: 140,
    nextAvailable: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    availability: [
      { day: 'Tuesday', times: ['10:00 AM', '1:00 PM', '5:00 PM'] },
      { day: 'Thursday', times: ['9:00 AM', '3:00 PM'] },
    ],
  },
  {
    id: 'interviewer-5',
    name: 'David Kim',
    company: 'Apple',
    role: 'Software Engineer',
    experience: 6,
    avatar: 'https://avatar.vercel.sh/user?u=davidkim',
    bio: 'Swift and Python expert. Friendly interviewer who focuses on learning.',
    skills: ['Swift', 'Python', 'DSA', 'System Design', 'Mobile Dev'],
    rating: 4.8,
    reviewCount: 234,
    pricePerSession: 110,
    nextAvailable: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    availability: [
      { day: 'Monday', times: ['3:00 PM', '6:00 PM'] },
      { day: 'Wednesday', times: ['1:00 PM', '5:00 PM'] },
      { day: 'Sunday', times: ['10:00 AM', '2:00 PM'] },
    ],
  },
]

export const mockInterviews: Interview[] = [
  {
    id: 'interview-1',
    candidateId: 'user-1',
    interviewerId: 'interviewer-1',
    interviewer: mockInterviewers[0],
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    duration: 60,
    type: 'System Design',
    status: 'scheduled',
    price: 120,
    notes: 'Focus on designing a rate limiting service',
    recordingUrl: null,
    transcriptUrl: null,
  },
  {
    id: 'interview-2',
    candidateId: 'user-1',
    interviewerId: 'interviewer-2',
    interviewer: mockInterviewers[1],
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: 45,
    type: 'Behavioral',
    status: 'completed',
    price: 150,
    notes: 'Tell me about your leadership experience',
    recordingUrl: 'https://example.com/interview-1.mp4',
    transcriptUrl: 'https://example.com/interview-1.txt',
  },
]

export const mockFeedback: Feedback = {
  id: 'feedback-1',
  interviewId: 'interview-2',
  communicationClarity: 7.5,
  technicalDepth: 8.2,
  confidence: 7.8,
  problemSolving: 8.0,
  strengths: [
    'Excellent communication of thought process',
    'Strong technical foundation',
    'Good follow-up questions',
  ],
  weaknesses: [
    'Could work on more concise explanations',
    'Handling edge cases could be more systematic',
  ],
  improvementPlan: [
    'Practice explaining complex topics in simpler terms',
    'Work through more system design scenarios',
    'Focus on edge cases during practice',
  ],
  recommendedResources: [
    'System Design Interview - Alex Xu',
    'Cracking the Coding Interview - Gayle McDowell',
    'System Design Primer - GitHub Repository',
  ],
  overallScore: 7.9,
  generatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
}

export const trustBadges = [
  { name: 'Google', icon: '🔍' },
  { name: 'Amazon', icon: '📦' },
  { name: 'Microsoft', icon: '💻' },
  { name: 'Meta', icon: '👥' },
  { name: 'Apple', icon: '🍎' },
]
